#!/bin/bash
# =============================================================================
# setup-env.sh — One-time Android Dev Environment Setup for WSL
# Jalankan sekali: bash setup-env.sh
# Setelah itu, semua variabel akan otomatis tersedia di setiap sesi WSL.
# =============================================================================

BASHRC="$HOME/.bashrc"
MARKER="# >>> Android Dev Environment <<<"

# Cek apakah sudah pernah di-setup sebelumnya
if grep -q "$MARKER" "$BASHRC" 2>/dev/null; then
    echo "✅ Environment sudah terdaftar di $BASHRC"
    echo "   Untuk memperbarui, hapus blok antara:"
    echo "   '$MARKER' dan '# >>> End Android Dev <<<'"
    echo ""
    echo "   Lalu jalankan script ini lagi."
    exit 0
fi

# Tulis blok env ke ~/.bashrc
cat >> "$BASHRC" << 'EOF'

# >>> Android Dev Environment <<<
# Auto-generated by setup-env.sh — jangan edit manual

export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
export ANDROID_HOME=/mnt/f/AndroidSDK
export ANDROID_SDK_ROOT=$ANDROID_HOME   # alias yang dikenali Gradle & AGP

# Gradle (WSL path)
export GRADLE_HOME=/mnt/f/.gradle_wsl/gradle-8.7
export GRADLE_USER_HOME=/mnt/f/.gradle_wsl  # cache di Windows drive, bukan di WSL home

# PATH: Gradle → Android tools → platform-tools
export PATH=$GRADLE_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

# Alias praktis
alias abuild='gradle assembleDebug'
alias ainstall='gradle installDebug'
alias aclean='gradle clean'
alias aupload='/mnt/f/New\ folder/telegram-upload.sh'
alias acheck='gradle lint'

alias atasks='gradle tasks --all'


# >>> End Android Dev <<<
EOF

echo ""
echo "✅ Berhasil! Variabel berikut telah ditambahkan ke $BASHRC:"
echo ""
echo "   JAVA_HOME         = /usr/lib/jvm/java-21-openjdk-amd64"
echo "   ANDROID_HOME      = /mnt/f/AndroidSDK"
echo "   ANDROID_SDK_ROOT  = /mnt/f/AndroidSDK"
echo "   GRADLE_HOME       = /mnt/f/.gradle_wsl/gradle-8.7"

echo "   GRADLE_USER_HOME  = /mnt/f/.gradle_wsl"

echo ""
echo "   Aliases: abuild, ainstall, aclean, acheck, atasks"
echo ""
echo "👉 Aktifkan sekarang tanpa restart WSL:"
echo "   source ~/.bashrc"
echo ""
